### ISSUE TITLE
Cadastro no grupo do Slack não está funcionando

### ISSUE THREAD

**Issue by giovannibonetti** [jonduarte/rubytalk#4]
Tentei me cadastrar no grupo do Slack mas não deu certo:

![Screenshot 2019-05-21 16 18 51](https://user-images.githubusercontent.com/3451581/58124245-2a109300-7be4-11e9-9242-a27d002eb71d.png)

Depois tentei de volta com o mesmo email e o erro foi este:

![Screenshot 2019-05-21 16 20 28](https://user-images.githubusercontent.com/3451581/58124361-6d6b0180-7be4-11e9-9023-582f7406680b.png)

Por último, tentei usar a função "recuperar minha senha" do grupo do Slack e também não deu certo:

![Screenshot 2019-05-21 16 22 00](https://user-images.githubusercontent.com/3451581/58124522-c9358a80-7be4-11e9-8e49-6c9545a9c74a.png)

**Comment by jonduarte** [comment]
Olá @giovannibonetti - Obrigado por reportar o erro.
Eu já arrumei e você deve receber o invite em breve.
